# Generated by Django 4.2.12 on 2024-12-24 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ip_address',
            field=models.GenericIPAddressField(default=0),
        ),
        migrations.CreateModel(
            name='IPTracking',
            fields=[
                ('ip_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('review_count', models.IntegerField(default=0)),
                ('flagged_as_fake', models.BooleanField(default=False)),
                ('last_review_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_tracking', to='myapp.product')),
            ],
            options={
                'unique_together': {('ip_address', 'product')},
            },
        ),
    ]
