# Generated by Django 4.2.12 on 2024-12-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_comment_ip_address_iptracking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='iptracking',
            unique_together=set(),
        ),
    ]
