# Generated by Django 4.2.12 on 2024-12-24 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_comment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptracking',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_tracking', to='myapp.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ip_address',
            field=models.GenericIPAddressField(default='00000'),
        ),
    ]
